apiVersion: batch/v1
kind: CronJob
metadata:
  name: bluesky-autoupload
  namespace: {{ .Values.namespace }}
spec:
  schedule: "45 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bluesky-autoupload
              image: lnadev/bluesky-autoupload:{{ .Values.autoupload.bluesky.version }}
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  memory: "128Mi"
              env:
                - name: BLUESKY_PAT
                  valueFrom:
                    secretKeyRef:
                      name: bluesky
                      key: pat
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: personal-api-secret
                      key: apikey
          restartPolicy: Never
      backoffLimit: 0