apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: personal-website
          image: nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 80
              name: port-http
          volumeMounts:
            - name: personal-website-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: personal-website-storage
          persistentVolumeClaim:
            claimName: {{ .Values.homePage.pvcName }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: personal-website-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: personal-website
---
apiVersion: v1
kind: Service
metadata:
  name: personal-website-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: personal-website
  ports:
    - port: 80
      targetPort: port-http
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: personal-redirectscheme@kubernetescrd
spec:
  tls:
  - hosts:
      - "lna-dev.net"
      - "www.lna-dev.net"
    secretName: personal-website-cert
  rules:
    - host: lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: www.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-redirection-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: personal-redirectscheme-personal-website@kubernetescrd
spec:
  tls:
    - hosts:
        - "lna-dev.de"
        - "lna-dev.com"
      secretName: personal-website-redirection-cert
  rules:
    - host: lna-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: lna-dev.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-redirection-ingress-http
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: personal-redirectscheme-personal-website@kubernetescrd
spec:
  rules:
    - host: lna-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: lna-dev.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---
# Needed because of HTTP to HTTPS redirecting
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress-http
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: personal-redirectscheme@kubernetescrd
spec:
  rules:
    - host: lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: www.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme-personal-website
  namespace: {{ .Values.namespace }}
spec:
  redirectRegex:
    regex: '.*'
    replacement: "https://lna-dev.net"
    permanent: true
