apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photo-website-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: redirect-photo-lna@kubernetescrd
spec:
  tls:
    - hosts:
        - "photo.lna-dev.net"
        - "www.photo.lna-dev.net"
      secretName: personal-website-photo-cert
  rules:
    - host: photo.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: www.photo.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photo-website-ingress-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: redirect-photo-lna@kubernetescrd
spec:
  rules:
    - host: photo.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80
    - host: www.photo.lna-dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website-service
                port:
                  number: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-photo-lna
spec:
  redirectRegex:
    regex: '^(https?)://photo\.lna-dev\.net/(.*)'
    replacement: 'https://lna-dev.net/en/gallery'
    permanent: true
