name: Release Chart

on:
  workflow_dispatch:

  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: "lnadev"

jobs:
  ReleaseVersion:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Publish
      - name: Push Helm Chart to DockerHub
        uses: bsord/helm-push@v4.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          access-token: ${{ secrets.DOCKERHUB_TOKEN }}
          registry-url: 'oci://registry-1.docker.io/${{ env.DOCKERHUB_USERNAME }}'
          force: true
          chart-folder: .
          useOCIRegistry: true

      # Setup kubeconfig
      - name: base64-to-file
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "custom-config"
          encodedString: ${{ secrets.KUBECTL_CONFIG }}

      # Install chart
      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Install Helm chart
        run: |
          helm init --skip-refresh
          helm pull oci://registry-1.docker.io/lnadev/charts.personal
          helm upgrade --install charts.personal oci://registry-1.docker.io/lnadev/charts.personal --namespace personal